version: '3.8'
services:
  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: .
      # target: development
    volumes:
      - apithesame:/data/postgres-the-same/api
    env_file:
      - .env
    command: npm run start
    ports:
      - 3456:3456
    depends_on:
      - postgres
      - pgadmin

  postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - '5432:5432'
    volumes:
      - dbthesame:/data/postgres-the-same/data

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - '8089:80'
    volumes:
      - pgadmin-data:/data/the-same-postgres/admin
volumes:
  apithesame:
  dbthesame:
  pgadmin-data:
